# Generated by Django 4.2.30 on 2026-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(max_length=32, unique=True, verbose_name="uuid"),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="song_covers/"),
                ),
                ("audio_file", models.FileField(upload_to="songs/%Y/%m/%d/")),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateTimeField(auto_now_add=True)),
                ("genre", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("play_count", models.PositiveBigIntegerField(default=0)),
                ("like_count", models.PositiveBigIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("duration", models.DurationField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "song",
                "verbose_name_plural": "songs",
                "db_table": "song",
            },
        ),
    ]
