# Generated by Django 4.2.30 on 2026-07-24 14:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uuid', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(help_text='Enter stage name', max_length=20, unique=True)),
                ('first_name', models.CharField(help_text='Enter first name', max_length=25, unique=True)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=45, unique=True)),
                ('gender', models.CharField(choices=[('he/him', 'he/him'), ('she/her', 'she/her'), ('he/him', 'he/him'), ('they/them', 'they/them'), ('custom', 'custom'), ('they/them', 'they/them')], help_text='Select your gender from the list', max_length=10)),
                ('country', django_countries.fields.CountryField(help_text='Enter country', max_length=20)),
                ('dob', models.DateField(help_text='Enter date of brith', max_length=8)),
                ('avatar', models.ImageField(blank=True, help_text='Upload your desired profile avatar', null=True, upload_to='media/artist/avatar/')),
                ('baner', models.ImageField(blank=True, help_text='Upload your desired profile baner', null=True, upload_to='media/artist/baner/')),
                ('email', models.EmailField(help_text='Enter email', max_length=254, unique=True)),
                ('followers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'artist',
            },
        ),
    ]
