# Generated by Django 4.2.30 on 2026-07-26 16:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, db_index=True, help_text='Upload your desired profile avatar', null=True, upload_to='media/artist/avatar/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='baner',
            field=models.ImageField(blank=True, db_index=True, help_text='Upload your desired profile baner', null=True, upload_to='media/artist/baner/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, help_text='Enter country', max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_index=True, help_text='Enter stage name', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uuid',
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
    ]
