# Generated by Django 4.2.30 on 2026-09-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="song",
            table="songs",
        ),
    ]
