# Generated by Django 4.2.30 on 2026-09-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_song_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"verbose_name": "song", "verbose_name_plural": "songs"},
        ),
        migrations.AlterField(
            model_name="song",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name="song",
            table="song",
        ),
    ]
