# Generated by Django 4.2.30 on 2026-09-15 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_fingerprint_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_name",
            field=models.CharField(max_length=255, verbose_name="device name"),
        ),
        migrations.AlterField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="ip address"),
        ),
        migrations.AlterField(
            model_name="device",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last seen"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="uuid",
            field=models.CharField(max_length=32, unique=True, verbose_name="uuid"),
        ),
        migrations.AlterField(
            model_name="fingerprint",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.device",
                verbose_name="device",
            ),
        ),
        migrations.AlterField(
            model_name="fingerprint",
            name="key",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="fingerprint hash"
            ),
        ),
    ]
