# Generated by Django 4.2.30 on 2026-09-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_device_created_at_alter_device_device_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "device", "verbose_name_plural": "devices"},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
            },
        ),
        migrations.AlterModelTable(
            name="device",
            table="device",
        ),
        migrations.AlterModelTable(
            name="fingerprint",
            table="fingerprint",
        ),
        migrations.AlterModelTable(
            name="membership",
            table="membership",
        ),
    ]
