# Generated by Django 4.2.30 on 2026-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_device_options_alter_membership_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_name",
            field=models.CharField(max_length=512, verbose_name="device name"),
        ),
    ]
